In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

### Python List

In [4]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L[5] = 100

In [6]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
L[5] = 'PYTHON LIST'

In [8]:
L

[0, 1, 2, 3, 4, 'PYTHON LIST', 6, 7, 8, 9]

In [13]:
import array
# 有类型限制

In [10]:
arr = array.array('i', [i for i in range(10)])

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

### Numpy

In [14]:
# 同样是有类型限制
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [17]:
nparr.dtype

dtype('int32')

In [18]:
# 默认强转为原本array里面的类型
nparr[3] = 3.14
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr2 = np.array([1, 2, 5.1])

In [21]:
nparr2.dtype

dtype('float64')