### Numpy.array的基本操作

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(-1, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [5]:
# 1. 维度
x.ndim

1

In [6]:
X.ndim

2

In [7]:
# 2. 矩阵大小
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
# 元素数量
x.size

10

In [10]:
X.size

15

### Numpy.array 的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[2][2]

12

In [17]:
X[(2, 2)]

12

In [18]:
X[2, 2]

12

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
# 倒着访问
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [30]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [32]:
X[1]

array([5, 6, 7, 8, 9])

In [33]:
X[1, :]

array([5, 6, 7, 8, 9])

In [34]:
X[1, :].ndim

1

In [35]:
X[:, 1]

array([ 1,  6, 11])

In [36]:
X[:, 1].ndim

1

In [37]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])


- python里面切片会创建全新的矩阵
- numpy里面直接将应用返回
- 使用numpy.array.copy()方法进行拷贝，会创建新对象

In [38]:
# 此时会修改原矩阵
# python里面切片会创建全新的矩阵
# numpy里面直接将应用返回
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [39]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [40]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [41]:
X[0][0] = 0

In [42]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

### Reshape
- 不改变原对象

In [44]:
x.shape

(10,)

In [45]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
A = x.reshape(1, 10)
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
A.ndim

2

### 合并操作

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [50]:
x

array([1, 2, 3])

In [51]:
y

array([3, 2, 1])

In [52]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [53]:
z = np.array([123, 123, 123])

In [54]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 123, 123, 123])

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [58]:
B = np.concatenate([A, A])
B

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
B.ndim

2

In [60]:
A[0, 0] = 100
A

array([[100,   2,   3],
       [  4,   5,   6]])

In [61]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
A[0, 0] = 1

In [64]:
C = np.concatenate([A, A], axis=1)
C

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [65]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [123, 123, 123]])

In [66]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [123, 123, 123]])

In [70]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [71]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [72]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x1, x2, x3 = np.split(x, [3, 7])

In [76]:
x1

array([0, 1, 2])

In [77]:
x2

array([3, 4, 5, 6])

In [78]:
x3

array([7, 8, 9])

In [79]:
x1, x2 = np.split(x, [5])

In [80]:
x1

array([0, 1, 2, 3, 4])

In [81]:
x2

array([5, 6, 7, 8, 9])

In [82]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
A1, A2 = np.split(A, [2])

In [84]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
A1, A2 = np.split(A, [2], axis=1)

In [87]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [88]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [89]:
A1, A2 = np.vsplit(A, [2])

In [90]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
A1, A2 = np.hsplit(A, [2])

In [93]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [94]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
# 此时可将最后一列看做标签，将其拆开
data = np.arange(16).reshape((4, -1))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
X, y = np.hsplit(data, [-1])

In [102]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [103]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])