### 聚合操作

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
L

array([0.79250283, 0.42906354, 0.10783121, 0.96900265, 0.74207287,
       0.55077904, 0.46822737, 0.24746048, 0.85294278, 0.05008846,
       0.91390956, 0.66206038, 0.43287705, 0.33886529, 0.17122292,
       0.16325962, 0.7403932 , 0.61628825, 0.2902702 , 0.85651609,
       0.01527784, 0.60681007, 0.61915335, 0.90862456, 0.63507756,
       0.73887901, 0.34091191, 0.45861166, 0.64691612, 0.69600218,
       0.73413324, 0.9330945 , 0.26576997, 0.39504446, 0.80426169,
       0.85599857, 0.81353931, 0.25918544, 0.71463236, 0.68192098,
       0.13845104, 0.67046561, 0.54020699, 0.42706906, 0.70729831,
       0.22326634, 0.03151527, 0.39952396, 0.84810221, 0.13945073,
       0.23932946, 0.93128121, 0.89907098, 0.38435557, 0.40065324,
       0.44845243, 0.44306522, 0.64785724, 0.95510603, 0.72327817,
       0.0879621 , 0.97887133, 0.59030618, 0.6615794 , 0.44874435,
       0.33321262, 0.13997655, 0.05878939, 0.82667928, 0.24644347,
       0.0013874 , 0.14708298, 0.11951621, 0.27348778, 0.98051

In [4]:
sum(L)

53.47595775862643

In [5]:
np.sum(L)

53.47595775862645

In [6]:
big_arr = np.random.random(1000000)
%timeit sum(big_arr)
%timeit np.sum(big_arr)

76.3 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.07 ms ± 28.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_arr)

2.268679692996045e-07

In [8]:
np.max(big_arr)

0.9999999585154664

In [9]:
big_arr.min()

2.268679692996045e-07

In [10]:
big_arr.sum()

499740.26794238813

In [11]:
X = np.arange(16).reshape(4, -1)

In [12]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X)

120

### axis 沿着哪个轴进行压缩
> 1. axis=0, 沿着行方向压缩
> 2. axis=1, 沿着列方向压缩

In [14]:

np.sum(X, axis=0)

array([24, 28, 32, 36])

In [15]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [17]:
# 返回所有乘积
np.prod(X)

0

In [18]:
np.prod(X+1)

2004189184

In [19]:
np.mean(X)

7.5

In [21]:
# 中位数
np.median(X)

7.5

In [22]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [23]:
np.median(v)

2.0

In [24]:
# 百分位  50% 此时就是中位数
np.percentile(big_arr, q=50)

0.49967102586721984

In [25]:
np.median(big_arr)

0.49967102586721984

In [26]:
for per in [0, 25, 50, 75, 100]:
    print(np.percentile(big_arr, q=per))

2.268679692996045e-07
0.24958708848814376
0.49967102586721984
0.7495101107428453
0.9999999585154664


In [27]:
# 方差
np.var(big_arr)

0.083362849820399

In [29]:
# 标准差
np.std(big_arr)

0.2887262541238656

In [33]:
x = np.random.normal(0, 1, size=1000000)

In [34]:
np.mean(x)

0.00038249215719023024

In [35]:
np.std(x)

1.0013504128232975

### 索引

In [36]:
np.min(x)

-4.659064781714484

In [38]:
# 最小值的索引
np.argmin(x)

96352

In [39]:
x[96352]

-4.659064781714484

In [40]:
np.argmax(x)

261898

### 排序和使用索引

In [42]:
x = np.arange(16)

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
# 乱序
np.random.shuffle(x)

In [45]:
x

array([ 0,  4, 11,  3, 15, 10,  2,  7,  8,  5,  1,  9, 13,  6, 12, 14])

In [46]:
# 排序，并未改变x
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
# 使用x.sort()方法进行修改x
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
X = np.random.randint(10, size=(4, 4))
X

array([[4, 8, 8, 7],
       [5, 0, 4, 5],
       [3, 1, 6, 6],
       [1, 2, 3, 1]])

In [51]:
np.sort(X)

array([[4, 7, 8, 8],
       [0, 4, 5, 5],
       [1, 3, 6, 6],
       [1, 1, 2, 3]])

In [52]:
np.sort(X, axis=1)

array([[4, 7, 8, 8],
       [0, 4, 5, 5],
       [1, 3, 6, 6],
       [1, 1, 2, 3]])

In [53]:
np.sort(X, axis=0)

array([[1, 0, 3, 1],
       [3, 1, 4, 5],
       [4, 2, 6, 6],
       [5, 8, 8, 7]])

In [54]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
np.random.shuffle(x)

In [56]:
x

array([12, 13,  8, 15,  4, 14,  0,  6, 10,  1,  5,  2,  3,  7,  9, 11])

In [62]:
# 排好序后返回原先所有元素对应的索引
a = np.argsort(x)
a

array([ 6,  9, 11, 12,  4, 10,  7, 13,  2, 14,  8, 15,  0,  1,  5,  3],
      dtype=int64)

In [61]:
x[a]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
x

array([12, 13,  8, 15,  4, 14,  0,  6, 10,  1,  5,  2,  3,  7,  9, 11])

In [65]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  9, 10,  8,  7, 11, 13, 14, 15, 12])

In [66]:
np.argpartition(x, 3)

array([ 6,  9, 11, 12,  4, 10,  7, 14,  8,  2, 13, 15,  1,  5,  3,  0],
      dtype=int64)

In [67]:
X

array([[4, 8, 8, 7],
       [5, 0, 4, 5],
       [3, 1, 6, 6],
       [1, 2, 3, 1]])

In [68]:
np.argsort(X)

array([[0, 3, 1, 2],
       [1, 2, 0, 3],
       [1, 0, 2, 3],
       [0, 3, 1, 2]], dtype=int64)

In [69]:
np.argsort(X, axis=0)

array([[3, 1, 3, 3],
       [2, 2, 1, 1],
       [0, 3, 2, 2],
       [1, 0, 0, 0]], dtype=int64)

In [70]:
np.partition(X, 3)

array([[4, 7, 8, 8],
       [4, 0, 5, 5],
       [1, 3, 6, 6],
       [1, 1, 2, 3]])