### 数据操作

In [24]:
import torch
torch.manual_seed(0)
torch.__version__

'1.3.1+cpu'

### 2.2.1 创建Tensor

> **创建一个5x3的未初始化的Tensor**

- torch.empty(5, 3)
- torch.rand(5, 3)
- torch.zeros(5, 3)
- torch.tensor([5, 3])
- x.new_ones(5, 3, dtype=torch.float) # 在现有的tensor上穿件新的tensor
- torch.rand_like(x, dtype=torch.float) # 根据x维度来创建随机tensor


In [25]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.2246e-39],
        [7.0295e+28, 6.1949e-04, 2.9390e+29],
        [2.0705e-19, 4.4721e+21, 7.5540e+31],
        [4.2964e+24, 1.7442e+28, 1.7033e+19]])

In [26]:
x = torch.rand(5, 3)
x

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])

In [27]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [28]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

通过现有的tensor来创建

In [29]:
x = x.new_ones(5, 3, dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [30]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.5185, 0.6977, 0.8000],
        [0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742],
        [0.4194, 0.5529, 0.9527],
        [0.0362, 0.1852, 0.3734]])

In [31]:
# 返回结果是tuple
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作

#### 算术操作

> 1. **加法形式一: x + y**
> 2. **加法形式二: torch.add(x, y)**
> 3. **加法形式三: x.add_(y), 此时为 x = x + y**

In [32]:
y = torch.rand(5, 3)
x + y

tensor([[0.8236, 1.6297, 0.9759],
        [0.4309, 0.4329, 0.7133],
        [1.1233, 1.3269, 1.5973],
        [1.1617, 1.0792, 1.1964],
        [0.6208, 0.2184, 0.5121]])

In [33]:
torch.add(x, y)

tensor([[0.8236, 1.6297, 0.9759],
        [0.4309, 0.4329, 0.7133],
        [1.1233, 1.3269, 1.5973],
        [1.1617, 1.0792, 1.1964],
        [0.6208, 0.2184, 0.5121]])

In [34]:
x.add_(y)

tensor([[0.8236, 1.6297, 0.9759],
        [0.4309, 0.4329, 0.7133],
        [1.1233, 1.3269, 1.5973],
        [1.1617, 1.0792, 1.1964],
        [0.6208, 0.2184, 0.5121]])

### 索引操作

> **torch的索引操作类似于numpy, 索引出来的结果与原数据共享内存**

In [35]:
z = x[0, :]
z

tensor([0.8236, 1.6297, 0.9759])

In [36]:
z.add_(1)
z

tensor([1.8236, 2.6297, 1.9759])

In [37]:
x[0, :]

tensor([1.8236, 2.6297, 1.9759])

### 改变形状

> 1. **通过tensor.view()改变形状**
> 2. **tensor.view()返回的新tensor与原tensor共享内存**
> 3. **通过tensor.clone()创造一个副本来进行修改**
> 4. **通过tensor.item()将一个标量tensor转化为python number**

In [39]:
y = x.view(15)
y.shape

torch.Size([15])

In [40]:
a = x.view(5, -1)
a.shape

torch.Size([5, 3])

In [41]:
x_cp = x.clone().view(15)
x_cp

tensor([1.8236, 2.6297, 1.9759, 0.4309, 0.4329, 0.7133, 1.1233, 1.3269, 1.5973,
        1.1617, 1.0792, 1.1964, 0.6208, 0.2184, 0.5121])

In [43]:
x -= 1

In [44]:
x_cp

tensor([1.8236, 2.6297, 1.9759, 0.4309, 0.4329, 0.7133, 1.1233, 1.3269, 1.5973,
        1.1617, 1.0792, 1.1964, 0.6208, 0.2184, 0.5121])

In [45]:
x

tensor([[ 0.8236,  1.6297,  0.9759],
        [-0.5691, -0.5671, -0.2867],
        [ 0.1233,  0.3269,  0.5973],
        [ 0.1617,  0.0792,  0.1964],
        [-0.3792, -0.7816, -0.4879]])

### 2.2.3 广播机制

> 1. **每个张量具有至少一个维度**
> 2. **在遍历维度大小时, 从尾部维度开始遍历, 两者维度必须"相同", 此处"相同"三种含义: 两者相等;其中一个是1;其中一个不存在**

In [48]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
z = x+y
print(y)
print(z)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [50]:
z - y

tensor([[1, 2],
        [1, 2],
        [1, 2]])

### 2.2.4 运算的内存开销

In [51]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
id(y) == id_before

False

In [52]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
id(y) == id_before

True

In [53]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # 等价于 y += x; y.add_(x)
id(y) == id_before

True

### 2.2.5 Tensor和Numpy相互转换

> 1. **tenfor -> numpy : tensor.numpy()**
> 1. **numpy -> tenfor : torch.from_numpy()**
> 1. **numpy()和from_numpy()产生的tensor和 numpy array使用的相同的内存**
> 4. **torch.tensor()会进行数据拷贝,返回的tensor不会和原来的数据共享存**

In [54]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [55]:
a += 1
print(a)
print(b)
b += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [56]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.]tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [57]:
a += 1
print(a, b)
b += 1
print(a, b)

[2. 2. 2. 2. 2.]tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.]tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [58]:
c = torch.tensor(a)
c += 1
print(a, c)

[3. 3. 3. 3. 3.]tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


### 2.2.6 Tensor On GPU

In [ ]:
if torch.cuda.is_available():
    device = torch.device('cuda')                 # GPU
    y = torch.ones_like(x, device=device)         # 创建一个在GPU上的tensor
    x = x.to(device)                              # 等价于 .to("cuda")
    z = x + y                                    
    z.to("cpu", torch.double)